# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
#  encoding: utf8
#  charset: utf8
#  collation: utf8_general_ci
  encoding: utf8mb4
  charset: utf8mb4
#  collation: utf8mb4_bin
  collation: utf8mb4_unicode_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: jiifactory
  username: root
  password:
  host: localhost

development:
  <<: *default

staging:
  <<: *default
  database: factory_staging
  username: factory
  password: factoryfactory_2018
  host: localhost

production:
  <<: *default
  database: factory
  username: root
  password: 
  host: localhost
