defaults: &defaults

  # サイト設定
  site_name: JiiFactory
  site_title: 案件管理
  site_description: Jiiの案件を管理するシステムです。

  # サイト画像
  logo:
  favicon:
  webclip:
  og_image:

  # home
  home: home

  # 未承認ユーザーのログインの許可設定 true: 許可する false: 許可しない
  allow_inactive_user: false
  # お知らせや通知等の新着表示期限(h)
  information_new_hours: 24

  # 請求額振込先
  payment_condition: '三菱UFJ銀行 神田支店 当座 0001776 カ）ニホンコウギョウシャ'

  consumption_tax: 1.08

  # 会社住所・電話番号
  jii_address: '東京都文京区白山2-37-7'
  jii_tel: '03-6881-0916'
  jii_fax: '050-3606-6900'

development:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
